
name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - nipype
  - pip:
      - git+https://github.com/oesteban/nibabel.git@enh/transforms#egg=nibabel
